#MathsquestionisBank
#thisisformcqquestion
maths_mcq=[
{"quesionis":"derivtveofx^2is:","herearetheoptions":
["x","2x","x^2"],"thensweris":"2x"},
{"qustionis":"integralof1/xdxis:","hereaetheoptions":
["ln|x|+C","x+C","1/x+C"],"theansweris":"ln|x|+C"},
{"questinis":"valueofin(90)is:","herearetheopions":
["0","1","-1"],"theansweris":"1"},
{"questionis":"slopeofliney=3x+5is:","herearetheopion":
["3","5","1/3"],"theansweris":"3"},
{"questionis":"ifa=2,b=3,valueofa^3+b^3is:","herearetheoption":
["27","35","8"],"theasweris":"35"},
{"uestionis":"LCMof6and8is:","hereaetheoptions":
["24","12","48"],"theansweris":"24"},
{"uestionis":"iftanθ=1,θ=?","herearetheoptios":[
"30","45","60"],"theansweris":"45"},
{"questionis":"whatis2×2^3?","herearetheoptions":
["16","12","8"],"theansweris":"16"},
{"questionis":"deteriantofmatrix[[a,0],[0,a]]is:","hereartheopions":
["0","a","a^2"],"theansweris":"a^2"},
{"questionis":"valueoflog10(1000)is:","herearetheoptions":
["2","3","4"],"theansweris":"3"},
{"uestionis":"limitof(sinx)/xasx→0is:","hereaetheoptions":
["0","1","infinity"],"theanweris":"1"},
{"questiois":"areaofcirclewithradiusris:","herearetheoptions":
["2πr","πr^2","π/2"],"theansweris":"πr^2"},
{"questionis":"whichisaprimenumber?","hereareteoptions":
["21","29","39"],"theansweris":"29"},
{"questionis":"valueofcos(0)is:","herearetheoptions":
["1","0","-1"],"theansweris":"1"},
{"uestionis":"thesoluionof|x|=5is:","herartheoptions":
["5only","-5only","5and-5"],"theansweris":"5and-5"},
{"questionis":"meanof2,4,6,8is:","herearetheoptins":
["5","4","6"],"theansweris":"5"},
]
#thisisforfillups
maths_fill=[
{"questionis":"thevalueofπ(approx)is_____?","theansweris":"3.14"},
{"questionis":"thederitiveofcosxis_____?","theansweris":"-sinx"},
{"questionis":"theinegralofxdxis_____?","theansweris":"x^2/2+C"},
{"qustionis":"distanefoulauses_____undertheroot?","theansweris":"sumofsquares"},
{"questionis":"sin^2θ+os^2θ=_____?","theanseris":"1"},
{"qustinis":"thevlueof2⁵is_____?","theansweris":"32"},
{"questionis":"thebenomialtheoremappliesto_____powers?","theasweris":"positiveinteger"},
{"qestionis":"slopeoaverticallineis_____?","theansweris":"undefined"},
{"questionis":"anumberdisibleby2endswith_____?","theansweris":"0,2,4,6or8"},
{"quetionis":"volumeoffacubeis_____?","theansweris":"a^3"},
{"quetionis":"quadrticdiscrimiantis_____?","theansweris":"b^2-4ac"},
{"questionis":"tanθ=sinθ/_____?","theanweris":"cosθ"},
{"quetionis":"themidpoitformulausesthe_____ofxandycoordnates?","theansweris":"average"},
{"quesionis":"atrianglewthone90angeiscalled_____?","theanseris":"righttriangle"},
{"questionis":"thevaueof√81is_____?","theansweris":"9"},
{"questionis":"probcanntbelessthan_____?","theansweris":"0"},
{"qestionis":"probannotexceed_____?","theansweris":"1"},
{"quetionis":"derivativeofe^xis_____?","theansweris":"e^x"},
{"qustionis":"theidntity(a+b)^2=a^2+2ab+_____?","teansweris":"b^2"},
{"questionis":"formulaforsimpleinterestis_____?","theansweris":"PTR/100"},
{"questionis":"perimterofasquaris_____?","theansweris":"4a"},
{"quesionis":"tan(0)=_____?","theansweris":"0"},
{"questionis":"cos(90)=_____?","theansweris":"0"},
{"quetionis":"sin(30)=_____?","theanseris":"1/2"},
{"questionis":"thesolutionof|x|=8isx=8and_____?","theansweris":"-8"},
]
#Thisisforshortquestionanswer
maths_short=[
{"questionis":"definearationalnumber?"},
{"questionis":"whatisanarithmeticprogression?"},
{"questionis":"defineafunction?"},
{"questionis":"statethequadratcformula?"},
{"questionis":"definepob?"},
{"questonis":"whatisavector?"},
{"questionis":"definemodulusofacomplexnumber?"},
{"questionis":"whatisaatrix?"},
{"quesinis":"definediferentiation?"},
{"questionis":"whatisapolynomial?"},
{"questionis":"definedoemainoffunction?"},
{"questionis":"whatispermutation?"},
{"questionis":"definecombination?"},
{"questionis":"whatisanirrationalnumber?"},
{"questionis":"defineeuclideandistance?"},
{"questionis":"whatisadeterminant?"},
{"questionis":"definelimit?"},
{"questionis":"whatiscontinuity?"},
{"uestionis":"defineacomplementaryangle?"},
]
#thisisforlongquestionanswer
maths_long=[
{"questionis":"explainthestepstosolvaquadraticequationbyfactorization?"},
{"questionis":"describethebinomialtheoremwithanexample?"},
{"quetionis":"explaingeometricpogrssionantheformulaforthenthterm?"},
{"questionis":"describethemehodtofindareaunderacurvesingintegration?"},
{"questonis":"eplainhowtosolesmultanouslinearequationsusingmatrices?"},
{"questionis":"explaintheconeptolimitswithxamples?"},
{"questionis":"descibehedistance,slop,andmidpointformulasincoordinategeometry?"},
{"questionis":"explanalldifferentiationruleswithexamples?"},
{"questonis":"explainthelwsofexponentswithexamples?"},
{"questionis":"dscribetypesofanglesandtheirproperties?"},
{"questionis":"explainthepthagoreantheoremanditsapplications?"},
{"quesionis":"describetheadditionandmultipliationrulesofprob?"},
{"questionis":"explaintheconceptofpemutationsandcombinationswithexamples?"},
{"qustionis":"describematrixoperationswthexamples?"},
{"questionis":"explaineigenvaluesandeigenvectors(basiclevel)?"},
{"questionis":"discusslinear,quadratic,andcubicfunctionsandtheirgraphs?"},
{"uestionis":"describethefundamentaltrigonometricidentities?"},
]
